// HEROES
export const LOAD_HEROES_SUCCESS = "LOAD_HEROES_SUCCESS";
export const SAVE_HERO_SUCCESS = "SAVE_HERO_SUCCESS";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";

// VILLAINS
export const LOAD_VILLAINS_SUCCESS = "LOAD_VILLAINS_SUCCESS";
export const SAVE_VILLAIN_SUCCESS = "SAVE_VILLAIN_SUCCESS";
export const DELETE_VILLAIN_SUCCESS = "DELETE_VILLAIN_SUCCESS";
