// HEROES
export const LOAD_HEROES_SUCCESS = "LOAD_HEROES_SUCCESS";
export const ADD_HERO = "ADD_HERO";
export const UPDATE_HERO = "UPDATE_HERO";
export const REMOVE_HERO = "REMOVE_HERO";

// VILLAINS
export const LOAD_VILLAINS_SUCCESS = "LOAD_VILLAINS_SUCCESS";
export const ADD_VILLAIN = "ADD_VILLAIN";
export const UPDATE_VILLAIN = "UPDATE_VILLAIN";
export const REMOVE_VILLAIN = "REMOVE_VILLAIN";
